/* Generated By:JJTree&JavaCC: Do not edit this line. ExprParserConstants.java */
package ariba.util.expr;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExprParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 67;
  /** RegularExpression Id. */
  int LETTER = 68;
  /** RegularExpression Id. */
  int DIGIT = 69;
  /** RegularExpression Id. */
  int DYNAMIC_SUBSCRIPT = 70;
  /** RegularExpression Id. */
  int ESC = 74;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 76;
  /** RegularExpression Id. */
  int BACK_CHAR_ESC = 77;
  /** RegularExpression Id. */
  int BACK_CHAR_LITERAL = 79;
  /** RegularExpression Id. */
  int STRING_ESC = 80;
  /** RegularExpression Id. */
  int STRING_LITERAL = 82;
  /** RegularExpression Id. */
  int INT_LITERAL = 83;
  /** RegularExpression Id. */
  int FLT_LITERAL = 84;
  /** RegularExpression Id. */
  int DEC_FLT = 85;
  /** RegularExpression Id. */
  int DEC_DIGITS = 86;
  /** RegularExpression Id. */
  int EXPONENT = 87;
  /** RegularExpression Id. */
  int FLT_SUFF = 88;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinCharLiteral = 1;
  /** Lexical state. */
  int WithinBackCharLiteral = 2;
  /** Lexical state. */
  int WithinStringLiteral = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"=\"",
    "\"def\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"or\"",
    "\"&&\"",
    "\"and\"",
    "\"|\"",
    "\"bor\"",
    "\"^\"",
    "\"xor\"",
    "\"&\"",
    "\"band\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"neq\"",
    "\"<\"",
    "\"lt\"",
    "\">\"",
    "\"gt\"",
    "\"<=\"",
    "\"lte\"",
    "\">=\"",
    "\"gte\"",
    "\"in\"",
    "\"not\"",
    "\"<< \"",
    "\"shl\"",
    "\">>\"",
    "\"shr\"",
    "\">>>\"",
    "\"ushr\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"~\"",
    "\"!\"",
    "\"instanceof\"",
    "\".\"",
    "\"@(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"it\"",
    "\"this\"",
    "\"thisField\"",
    "\"loginUser\"",
    "\"(\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"@\"",
    "\"new\"",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "<DYNAMIC_SUBSCRIPT>",
    "\"`\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ESC>",
    "<token of kind 75>",
    "\"\\\'\"",
    "<BACK_CHAR_ESC>",
    "<token of kind 78>",
    "\"`\"",
    "<STRING_ESC>",
    "<token of kind 81>",
    "\"\\\"\"",
    "<INT_LITERAL>",
    "<FLT_LITERAL>",
    "<DEC_FLT>",
    "<DEC_DIGITS>",
    "<EXPONENT>",
    "<FLT_SUFF>",
  };

}
