/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.1_3 */
package ariba.util.expr;

public interface ExprParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSEQUENCE = 1;
  public int JJTASSIGN = 2;
  public int JJTVARDECL = 3;
  public int JJTTEST = 4;
  public int JJTOR = 5;
  public int JJTAND = 6;
  public int JJTBITOR = 7;
  public int JJTXOR = 8;
  public int JJTBITAND = 9;
  public int JJTEQ = 10;
  public int JJTNOTEQ = 11;
  public int JJTLESS = 12;
  public int JJTGREATER = 13;
  public int JJTLESSEQ = 14;
  public int JJTGREATEREQ = 15;
  public int JJTIN = 16;
  public int JJTNOTIN = 17;
  public int JJTSHIFTLEFT = 18;
  public int JJTSHIFTRIGHT = 19;
  public int JJTUNSIGNEDSHIFTRIGHT = 20;
  public int JJTADD = 21;
  public int JJTSUBTRACT = 22;
  public int JJTMULTIPLY = 23;
  public int JJTDIVIDE = 24;
  public int JJTREMAINDER = 25;
  public int JJTNEGATE = 26;
  public int JJTBITNEGATE = 27;
  public int JJTNOT = 28;
  public int JJTINSTANCEOF = 29;
  public int JJTCAST = 30;
  public int JJTCHAIN = 31;
  public int JJTCONST = 32;
  public int JJTTHISVARREF = 33;
  public int JJTROOTVARREF = 34;
  public int JJTTHISFIELDVARREF = 35;
  public int JJTLOGINUSERVARREF = 36;
  public int JJTMAP = 37;
  public int JJTLIST = 38;
  public int JJTKEYVALUE = 39;
  public int JJTSTATICFIELD = 40;
  public int JJTCTOR = 41;
  public int JJTPROPERTY = 42;
  public int JJTSTATICMETHOD = 43;
  public int JJTMETHOD = 44;
  public int JJTPROJECT = 45;
  public int JJTINDEX = 46;


  public String[] jjtNodeName = {
    "void",
    "Sequence",
    "Assign",
    "VarDecl",
    "Test",
    "Or",
    "And",
    "BitOr",
    "Xor",
    "BitAnd",
    "Eq",
    "NotEq",
    "Less",
    "Greater",
    "LessEq",
    "GreaterEq",
    "In",
    "NotIn",
    "ShiftLeft",
    "ShiftRight",
    "UnsignedShiftRight",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Remainder",
    "Negate",
    "BitNegate",
    "Not",
    "Instanceof",
    "Cast",
    "Chain",
    "Const",
    "ThisVarRef",
    "RootVarRef",
    "ThisFieldVarRef",
    "LoginUserVarRef",
    "Map",
    "List",
    "KeyValue",
    "StaticField",
    "Ctor",
    "Property",
    "StaticMethod",
    "Method",
    "Project",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=03e9cc829e2e8de618b6c72bd1a1b13f (do not edit this line) */
