/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package ariba.ui.meta.core;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 28;
  /** RegularExpression Id. */
  int KEYPATH = 29;
  /** RegularExpression Id. */
  int FIELDPATHBINDING = 30;
  /** RegularExpression Id. */
  int LOCALIZATION_KEY = 31;
  /** RegularExpression Id. */
  int ESC = 34;
  /** RegularExpression Id. */
  int STRING_ESC = 35;
  /** RegularExpression Id. */
  int STRING_LITERAL = 37;
  /** RegularExpression Id. */
  int SQ_STRING_LITERAL = 39;
  /** RegularExpression Id. */
  int INT_LITERAL = 40;
  /** RegularExpression Id. */
  int FLT_LITERAL = 41;
  /** RegularExpression Id. */
  int DEC_FLT = 42;
  /** RegularExpression Id. */
  int DEC_DIGITS = 43;
  /** RegularExpression Id. */
  int EXPONENT = 44;
  /** RegularExpression Id. */
  int FLT_SUFF = 45;
  /** RegularExpression Id. */
  int EXPR_LITERAL = 53;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 54;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int WithinStringLiteral = 2;
  /** Lexical state. */
  int WithinSQStringLiteral = 3;
  /** Lexical state. */
  int WithinExprLiteral = 4;
  /** Lexical state. */
  int WithinExprLiteralNested = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"#\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\":\"",
    "\"!\"",
    "\"*\"",
    "\"=>\"",
    "\"@\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"~\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 27>",
    "<IDENT>",
    "<KEYPATH>",
    "<FIELDPATHBINDING>",
    "<LOCALIZATION_KEY>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<ESC>",
    "<STRING_ESC>",
    "<token of kind 36>",
    "\"\\\"\"",
    "<token of kind 38>",
    "\"\\\'\"",
    "<INT_LITERAL>",
    "<FLT_LITERAL>",
    "<DEC_FLT>",
    "<DEC_DIGITS>",
    "<EXPONENT>",
    "<FLT_SUFF>",
    "\"${\"",
    "\"$${\"",
    "\"{\"",
    "<token of kind 49>",
    "\"{\"",
    "<token of kind 51>",
    "\"}\"",
    "\"}\"",
    "<UNEXPECTED_CHAR>",
  };

}
